### ISSUE TITLE
[WIP] Ratpack 2 & Java 9+ Roadmap

### ISSUE THREAD

**Issue by johnrengelman** [ratpack/ratpack#1387]
This ticket is to capture the action plan for Ratpack to being supporting Java version starting with version 9 and beyond. Due to some of Java 9's changes to support Java Modules, Ratpack has become non-compliant to some of the tooling. Supporting 9+ will be a multi-phased approach which necessitates breaking API changes in Ratpack, requiring a major version increment.

## Related Issues
* https://github.com/ratpack/ratpack/issues/1273
* https://github.com/ratpack/ratpack/issues/1221
* https://github.com/ratpack/ratpack/issues/1279

## Proposed Roadmap

- [ ] Modifications to Ratpack to support compiling with JDK9 (compiling for Java 8 source and target compatibility). This does not include support for discovering Ratpack via Java's module system.
  - [ ] Remove references to internal Sun packages so that Ratpack does not require any `--add-modules` declarations.
  - [ ] Update CI to compile using a JDK9 binary.
    - [ ] `ratpack-test-internal` fails to compile on Java 9 due to a Groovy issue (https://github.com/apache/groovy/commit/68fc0d34dcc573de9658bb3a45ab32b200b543b8). That issue will be fixed in Groovy 2.5. We cannot upgrade to Groovy 2.5 because we compile internal projects for testing against `gradleTestKit()` which is currently limited to the 2.4.x line. Gradle 5 will introduce Groovy 2.5.
- [ ] Support Java9 modules - this requires a Ratpack major version.
  - [ ] Update packages so that each JAR exports a specific and unique package path. 
  - [ ] Unwind the `ratpack-base`, `ratpack-exec`, `ratpack-core` mess. Specifically the `ratpack.func` package being split
  - [ ] namespace each subproject package into a unique root path where it is not currently happening (ratpack-core, ratpack-exec).
- [ ] Extending Ratpack beyond HTTP. These changes could be done within the 2.0.0 release or we could release 2.0.0 as the Java9+ support and then increment another major version for these features. Effectively, this effort is to extend Ratpack beyond it's currently HTTP/1 implementation so that we can support alternative invocations such as HTTP/2, Message Queues, Kafka, etc.
  - [ ] Ensure that all the necessary pieces of Ratpack's execution model are standalone such that we can start building it as a reusable library outside of a Ratpack app
  - [ ] Ensure that all the necessary pieces of Ratpack's config system are standalone such taht we can start building it as a reusable library outside of a Ratpack app
  - [ ] Rename the API around `Context`, `Handler` to refer to them being the `HttpContext` and `HttpHandler` implementations, extending from a core `Context` and `Handler` type.
  - [ ] Refactor `RatpackServer` such that it is not HTTP specific, but instead takes a `RatpackServerType` (`RatpackServer.of(Action)` is thus then sugar for `RatpackServer.of(RatpackHttpServer.class, Action)`)
  - [ ] Decouple HTTP specific configuration from `ServerConfig` and make it typed based on the server type being configured.

**Comment by johnrengelman** [comment]
We have release `v1.6.0-rc-1` that among it's many features is the removal if internal `sun` packages. This version of ratpack is still compiled using the jdk 8 compiler with source/target compatibility for Java 8. 

In my testing, I've been able to compile and run Ratpack applications using this version with JDK/Java 9 in both Java 8 and Java 9 compatibility modes.

There is 1 warning issues when using Java 9:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/Users/z002ndy/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-all/2.4.15/423a17aeb2f64bc6f76e8e44265a548bec80fd42/groovy-all-2.4.15.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

If other users can test out `1.6.0-rc-1` against Java 9, 10, and 11 and post any issues on this ticket that would be greatly appreciated.

**Comment by johnrengelman** [comment]
https://github.com/ratpack/ratpack/pull/1524 is the begining of ratpack v2.0.0 on the `master` branch. 
Our first task is to fix the package problems. 
We've started documenting additional ideas/proposals for changes to v2 using the [v2-proposal label](https://github.com/ratpack/ratpack/labels/v2-proposal)

**Comment by msgilligan** [comment]
Have you thought about going JDK 11+ for v2.0.0? Ratpack was one of the first projects I followed that went JDK 8+ and that allowed it to be so forward-looking. Since JDK 11 is the LTS release, maybe v2.0.0 could just skip 9 & 10?

**Comment by johnrengelman** [comment]
Collapsed packages names for `ratpack-core` in https://github.com/ratpack/ratpack/pull/1537

**Comment by johnrengelman** [comment]
@msgilligan Ratpack already runs find on all the latest JVM versions. The "java 9+" as part of this ticket is to support the Java Module system introduced in Java 9 (aka Jigsaw) which requires that multiple jars on the classpath don't export the same package.

**Comment by msgilligan** [comment]
I'm just suggesting if you're going to break backwards compatibility, why not increase the minimum required JDK to 11? It could save the team lots of work in the long run. I'm not sure what the Ratpack user community would expect in terms of continued support for JDK 8-10. I'm just being a devils advocate. I just think it was cool when Ratpack first came out how it leapfrogged ahead by requiring JDK 8.

I'm not sure which features of the newer JDKs really help you as a baseline. Maybe  `java.util.concurrent.Flow`? Async HTTP client? At the very least you have fewer JDKs to test and support.

**Comment by johnrengelman** [comment]
There isn't really anything compelling in the language IMO for require Java 11. 
I don't think we are going to increase the minimum java version as part of this change as there will be a lot of companies still targeting Java 8 for the forseeable future (see Amazon (https://aws.amazon.com/blogs/opensource/amazon-corretto-no-cost-distribution-openjdk-long-term-support/) support through at least 2023 and AdoptOpenJDK (https://adoptopenjdk.net/support.html) support through at least 2026)

The compatibility that we are talking about here isn't necessarily language compatibility but that of the applications written using Ratpack. By changing package names, we are breaking working apps which will require source code changes. By requiring newer Java version and then using those new language features, we'd be breaking an application through no fault of it's own. It would just be broke for the sake of being broken with no real benefit to the application as it could get all the same benefits by writing their application in Java 11 or later and compiling with a target of the Java 11 runtime.

This is inherently different than our choice to require Java 8 in the core ratpack library for 2 reasons: 1) there wasn't the promise of long term support for anything older than Java 8, and 2) Lambdas and interface default methods were compelling language features for writing a library in a clean and fluent way.

@ldaley any thing else you want to add (or contest I guess)?

**Comment by msgilligan** [comment]
@johnrengelman Makes sense to me.
